site_url: https://tranzitcafe.netlify.app

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# when using the default proxy server port for local git update
local_backend: true

# publish_mode: editorial_workflow # Allows you to save drafts before publishing them

media_folder: static/images # Media files will be stored in the repo under static/uploads
public_folder: /images # The src attribute for uploaded media will begin with /uploads

# nc-root: If Netlify CMS finds an element with this ID during initialization, it will mount within that element instead of creating its own.

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

i18n:
  structure: multiple_files
  locales: [hu, en] 

collections:

  - name: menu
    label: Napi menü
    folder: /src/napimenu
    #path: "{{slug}}"
    slug: "{{date}}"
    summary: "{{date}}"
    identifier_field: date
    delete: true
    create: true
    i18n: true
    #filter: {field: "type", value: "index"}
    fields:
      - label: Dátum
        name: date
        widget: datetime
        format: "YYYY-MM-DD"
        date_format: "YYYY-MM-DD"
        time_format: false
        i18n: duplicate
      - label: Leves
        name: soup
        widget: string
        required: false
        i18n: true
      - label: A menu
        name: menua
        widget: string
        required: false
        i18n: true
      - label: B menu
        name: menub
        widget: string
        required: false
        i18n: true
  - name: news
    label: Infó
    folder: /src/news
    #path: "{{slug}}"
    slug: "{{date}}"
    #summary: "{{date}}"
    #identifier_field: date
    delete: true
    create: true
    i18n: true
    #filter: {field: "type", value: "index"}
    fields:
      - label: Expiration date
        name: date
        widget: datetime
        format: "YYYY-MM-DD"
        date_format: "YYYY-MM-DD"
        time_format: false
        i18n: duplicate
      - label: Title
        name: title
        widget: string
        required: false
        i18n: true
      - label: Summary
        name: summary
        widget: string
        required: false
        i18n: true
      - label: Content
        name: body
        widget: markdown
        required: false
        i18n: true
